In [ ]:
pip install pandas

In [1]:
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings("ignore")

In [ ]:
a = np.array([1,2,"aa","bb",34,45])

print(a.dtype)
print(a)

<U21
['1' '2' 'aa' 'bb' '34' '45']

In [ ]:
s = pd.Series(a, index = list(range(10,16)))
print(s)

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [ ]:
lt = [1,2,"aa","bb",34,45]
type(lt)

list

In [ ]:
dict1 = {"Snake": 0, "Birds": 1, "Cats": 2, "Humans": 4}
mydict = pd.Series(dict1)
print(mydict)

Snake     0
Birds     1
Cats      2
Humans    4
dtype: int64

In [ ]:
data = pd.read_csv("/content/German-Credit_1.xls")

In [ ]:
data.head()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,0.0,67.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,22.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,49.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,1.0,53.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

In [ ]:
data.tail()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
995,996,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,30.0,0.0,1.0,0.0,0.0,0.0,0.0,3857.0,4.0,...,0.0,40.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
997,998,12.0,0.0,0.0,0.0,1.0,0.0,0.0,804.0,4.0,...,0.0,38.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
998,999,45.0,0.0,0.0,0.0,1.0,0.0,0.0,1845.0,4.0,...,1.0,23.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
999,1000,45.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,3.0,...,0.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
data.columns

Index(['OBS', 'DURATION', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO_TV',
       'EDUCATION', 'RETRAINING', 'AMOUNT', 'INSTALL_RATE', 'CO_APPLICANT',
       'GUARANTOR', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL',
       'RENT', 'OWN_RES', 'NUM_CREDITS', 'NUM_DEPENDENTS', 'TELEPHONE',
       'FOREIGN', 'RESPONSE'],
      dtype='object')

In [ ]:
df_sub = data["EDUCATION"]
df_sub.head()

0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: EDUCATION, dtype: float64

In [ ]:
data.mean()

OBS                500.500000
DURATION            20.917836
NEW_CAR              0.234234
USED_CAR             0.103103
FURNITURE            0.180180
RADIO_TV             0.279840
EDUCATION            0.050201
RETRAINING           0.097390
AMOUNT            3273.168687
INSTALL_RATE         2.972810
CO_APPLICANT         0.041331
GUARANTOR            0.052367
REAL_ESTATE          0.281974
PROP_UNKN_NONE       0.155086
AGE                 35.505051
OTHER_INSTALL        0.186680
RENT                 0.178427
OWN_RES              0.713998
NUM_CREDITS          1.406439
NUM_DEPENDENTS       1.156093
TELEPHONE            0.403015
FOREIGN              0.037223
RESPONSE             0.700100
dtype: float64

In [ ]:
data.std()

OBS                288.819436
DURATION            12.064656
NEW_CAR              0.423731
USED_CAR             0.304246
FURNITURE            0.384530
RADIO_TV             0.449146
EDUCATION            0.218469
RETRAINING           0.296636
AMOUNT            2826.183525
INSTALL_RATE         1.119055
CO_APPLICANT         0.199154
GUARANTOR            0.222877
REAL_ESTATE          0.450187
PROP_UNKN_NONE       0.362169
AGE                 11.342694
OTHER_INSTALL        0.389851
RENT                 0.383065
OWN_RES              0.452118
NUM_CREDITS          0.576302
NUM_DEPENDENTS       0.363126
TELEPHONE            0.490750
FOREIGN              0.189404
RESPONSE             0.458444
dtype: float64

In [ ]:
data.describe()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
count,1000.000000,998.000000,999.000000,999.000000,999.00000,997.000000,996.000000,996.000000,990.000000,993.000000,...,993.000000,990.000000,991.000000,992.000000,993.000000,994.000000,993.000000,995.000000,994.000000,997.000000
mean,500.500000,20.917836,0.234234,0.103103,0.18018,0.279840,0.050201,0.097390,3273.168687,2.972810,...,0.155086,35.505051,0.186680,0.178427,0.713998,1.406439,1.156093,0.403015,0.037223,0.700100
std,288.819436,12.064656,0.423731,0.304246,0.38453,0.449146,0.218469,0.296636,2826.183525,1.119055,...,0.362169,11.342694,0.389851,0.383065,0.452118,0.576302,0.363126,0.490750,0.189404,0.458444
min,1.000000,4.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,250.000000,1.000000,...,0.000000,19.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,250.750000,12.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1371.250000,2.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,500.500000,18.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2321.500000,3.000000,...,0.000000,33.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,750.250000,24.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,3970.500000,4.000000,...,0.000000,42.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000
max,1000.000000,72.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,18424.000000,4.000000,...,1.000000,75.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000

In [ ]:
data.describe(include = "all")

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
count,1000.000000,998.000000,999.000000,999.000000,999.00000,997.000000,996.000000,996.000000,990.000000,993.000000,...,993.000000,990.000000,991.000000,992.000000,993.000000,994.000000,993.000000,995.000000,994.000000,997.000000
mean,500.500000,20.917836,0.234234,0.103103,0.18018,0.279840,0.050201,0.097390,3273.168687,2.972810,...,0.155086,35.505051,0.186680,0.178427,0.713998,1.406439,1.156093,0.403015,0.037223,0.700100
std,288.819436,12.064656,0.423731,0.304246,0.38453,0.449146,0.218469,0.296636,2826.183525,1.119055,...,0.362169,11.342694,0.389851,0.383065,0.452118,0.576302,0.363126,0.490750,0.189404,0.458444
min,1.000000,4.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,250.000000,1.000000,...,0.000000,19.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,250.750000,12.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1371.250000,2.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,500.500000,18.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2321.500000,3.000000,...,0.000000,33.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,750.250000,24.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,3970.500000,4.000000,...,0.000000,42.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000
max,1000.000000,72.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,18424.000000,4.000000,...,1.000000,75.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000

In [ ]:
#loc and iloc in pandas (to access a subset of the data)

In [ ]:
data.loc[1:5, "NEW_CAR":"AMOUNT"] # [row range, column range]

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING  AMOUNT
1      0.0       0.0        0.0       1.0        0.0         0.0  5951.0
2      0.0       0.0        0.0       0.0        1.0         0.0  2096.0
3      0.0       0.0        1.0       0.0        0.0         0.0  7882.0
4      1.0       0.0        0.0       0.0        0.0         0.0  4870.0
5      0.0       0.0        0.0       0.0        1.0         0.0  9055.0

In [ ]:
s = pd.Series(a, index = list(range(10,16)))
s.loc[10:15]

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [1]:
data_sub = data["AMOUNT"]
data_sub.mean()

NameError: name 'data' is not defined